name: pms-test

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/node.Dockerfile
      target: test
    container_name: pms-test-node
    env_file: ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      FORCE_COLOR: 1
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/mysql.Dockerfile
    container_name: pms-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 2s
      timeout: 5s
      retries: 20
    restart: always

  redis:
    image: redis:8.2.0-alpine
    container_name: pms-test-redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--requirepass ${REDIS_PASSWORD}",
      ]

  mailhog:
    image: mailhog/mailhog
    container_name: pms-test-mailhog
    restart: always
